### ISSUE TITLE
Multiple languages

### ISSUE THREAD

**Issue by BenjaminHoegh** [KrzysiekJ/jekyll-i18n_tags#1]
When having multiple languages is it then possible to have the translations in separated files?

**Comment by KrzysiekJ** [comment]
You can specify multiple configuration files for Jekyll using the `--config` command line argument. However I suppose that if you specify multiple `translations` dictionaries, then only the last will prevail. Therefore I’m afraid that currently splitting translations into multiple files is not possible.
